// Словарь прототипа. Строки проходят scripts/typograph-ru.mjs: неразрывный пробел
// записан как \u00A0, кавычки — «ёлочки».
export default {
  'mk.app.title': 'Прототип Arc Science',
  'mk.screen.label': 'Экран',
  'mk.screen.research': 'Пульт исследования',
  'mk.screen.settings': 'Настройки',
  'mk.screen.diagnostics': 'Диагностика',
  'mk.screen.latex': 'Студия LaTeX',
  'mk.screen.logos': 'Варианты логотипа',
  'mk.screen.placeholder': 'Эта рабочая область вне прототипа S0.',

  'mk.search.open': 'Найти или запустить',
  'mk.search.heading': 'Найти или запустить',
  'mk.search.field': 'Рабочие области, задания и\u00A0действия',
  'mk.search.hint': 'Введите название задания или действие.',
  'mk.search.group.workspaces': 'Рабочие области',
  'mk.search.group.missions': 'Задания',
  'mk.search.group.actions': 'Действия',
  'mk.search.action.new_route': 'Открыть новый маршрут',
  'mk.search.action.approvals': 'Перейти к\u00A0очереди согласования',
  'mk.search.action.export': 'Выгрузить релизный комплект',
  'mk.logo.slot': 'Логотип в\u00A0шапке',

  'mk.missions.heading': 'Задания',
  'mk.mission.question': 'Вопрос',
  'mk.mission.round': 'Раунд {current}\u00A0из\u00A0{total}',
  'mk.mission.state.active': 'Ожидает согласования',
  'mk.mission.state.paused': 'Приостановлено',
  'mk.mission.state.done': 'Закрыто',
  'mk.mission.state.running': 'Выполняется',

  'mk.m1.title': 'Замена заряда в\u00A0контактном участке HyHEL-63',
  'mk.m1.question': 'Сохранит\u00A0ли замена заряда в\u00A0контактном участке 1DQJ связывание с\u00A0лизоцимом и\u00A0повысит\u00A0ли растворимость?',
  'mk.m2.title': 'Аллостерическая бороздка на\u00A0лёгкой цепи',
  'mk.m2.question': 'Бороздка за\u00A0CDR L1\u00A0— настоящий аллостерический участок или артефакт кристалла?',
  'mk.m3.title': 'Термическая стабильность исходного Fab',
  'mk.m3.question': 'До\u00A0какой температуры исходный Fab сохраняет форму контактного участка?',

  'mk.tab.overview': 'Обзор',
  'mk.tab.routes': 'Маршруты',
  'mk.tab.claims': 'Утверждения',
  'mk.tab.evidence': 'Доказательства',
  'mk.tab.activity': 'Ход работы',
  'mk.tab.approvals': 'Согласование',
  'mk.tab.release': 'Релиз',

  'mk.overview.believe': 'Что мы\u00A0считаем установленным',
  'mk.overview.believe.1': 'Контактный участок выдерживает одну замену заряда без потери связывания с\u00A0лизоцимом.',
  'mk.overview.believe.2': 'Растворимость растёт после замены; измерено на\u00A0трёх демонстрационных партиях.',
  'mk.overview.believe.3': 'Аллостерическая бороздка пока не\u00A0объяснена и\u00A0вынесена из\u00A0основного утверждения.',
  'mk.overview.change': 'Что заставит это пересмотреть',
  'mk.overview.change.1': 'Падение связывания более чем в\u00A0десять раз в\u00A0референсном анализе.',
  'mk.overview.change.2': 'Прирост растворимости, который исчезает при совпадающем буфере.',
  'mk.overview.change.3': 'Вторая кристаллическая форма без бороздки.',
  'mk.overview.next': 'Дальше',
  'mk.overview.next.1': 'Провести референсный анализ связывания на\u00A0двух уцелевших вариантах.',
  'mk.overview.next.2': 'Повторить измерение растворимости в\u00A0совпадающем буфере.',
  'mk.overview.next.3': 'Запросить вторую кристаллическую форму до\u00A0заявления о\u00A0бороздке.',

  'mk.lane.focused': 'В\u00A0работе',
  'mk.lane.warm': 'В\u00A0запасе',
  'mk.lane.parked': 'Отложено',
  'mk.route.hypothesis': 'Гипотеза',
  'mk.route.falsifier': 'Что опровергнет гипотезу',
  'mk.route.observation': 'Последнее наблюдение',
  'mk.route.next': 'Следующая проверка',
  'mk.route.basis': 'Основание',

  'mk.route.r1.title': 'Замена заряда в\u00A0контактном участке',
  'mk.route.r1.hypothesis': 'Замена одного скрытого заряда повышает растворимость и\u00A0не\u00A0трогает связывание.',
  'mk.route.r1.falsifier': 'Связывание падает более чем в\u00A0десять раз в\u00A0референсном анализе.',
  'mk.route.r1.observation': 'Два условных варианта из\u00A0трёх удержали связывание в\u00A0пределах двукратного отклонения.',
  'mk.route.r1.next': 'Референсный анализ связывания на\u00A0обоих уцелевших вариантах.',
  'mk.route.r1.basis': 'Площадь интерфейса из\u00A01DQJ и\u00A0две опубликованные замены.',
  'mk.route.r2.title': 'Растворимость в\u00A0совпадающем буфере',
  'mk.route.r2.hypothesis': 'Прирост растворимости сохраняется при совпадающем буфере.',
  'mk.route.r2.falsifier': 'Прирост исчезает при равной ионной силе.',
  'mk.route.r2.observation': 'В\u00A0совпадающем буфере измерена пока одна партия.',
  'mk.route.r2.next': 'Измерить две оставшиеся партии в\u00A0совпадающем буфере.',
  'mk.route.r2.basis': 'Демонстрационные записи партий из\u00A0набора прототипа.',
  'mk.route.r3.title': 'Аллостерическая бороздка за\u00A0CDR L1',
  'mk.route.r3.hypothesis': 'Бороздка связывает малый лиганд и\u00A0смещает контактный участок.',
  'mk.route.r3.falsifier': 'Во\u00A0второй кристаллической форме плотности в\u00A0бороздке нет.',
  'mk.route.r3.observation': 'Бороздка видна только в\u00A0одной кристаллической форме.',
  'mk.route.r3.next': 'Запросить вторую кристаллическую форму до\u00A0траты времени на\u00A0анализ.',
  'mk.route.r3.basis': 'Одна демонстрационная карта и\u00A0один расчёт стыковки.',
  'mk.route.r4.title': 'Обратная мутация в\u00A0каркасе',
  'mk.route.r4.hypothesis': 'Обратная мутация в\u00A0каркасе возвращает потерянные полкилокалории.',
  'mk.route.r4.falsifier': 'Стабильность не\u00A0меняется во\u00A0всей панели обратных мутаций.',
  'mk.route.r4.observation': 'Наблюдений нет: панель ещё не\u00A0заказана.',
  'mk.route.r4.next': 'Заказать панель из\u00A0четырёх вариантов, когда освободится прибор.',
  'mk.route.r4.basis': 'Только предсказание, без измерений.',
  'mk.route.r5.title': 'Гликановое экранирование контактного участка',
  'mk.route.r5.hypothesis': 'Добавленный гликан экранирует контактный участок и\u00A0снижает агрегацию.',
  'mk.route.r5.falsifier': 'Агрегация не\u00A0меняется при добавленном гликане.',
  'mk.route.r5.observation': 'Отложено: первый проход не\u00A0нашёл свободного сиквона.',
  'mk.route.r5.next': 'Вернуться, только если маршрут с\u00A0заменой заряда встанет.',
  'mk.route.r5.basis': 'Сканирование последовательности демонстрационной конструкции.',

  'mk.claim.requested': 'Запрошено',
  'mk.claim.scope': 'Подтверждённая область',
  'mk.claim.uncertainty': 'Неопределённость',
  'mk.claim.next': 'Следующий эксперимент',
  'mk.ladder': 'Лестница проверки',
  'mk.ladder.reached': 'Достигнута ступень {rung}',
  'mk.ladder.needs': 'Для следующей ступени нужно',
  'mk.ladder.l0': 'Заявлено',
  'mk.ladder.l1': 'С\u00A0источником',
  'mk.ladder.l2': 'Воспроизведено',
  'mk.ladder.l3': 'С\u00A0контролем',
  'mk.ladder.l4': 'Независимо',
  'mk.ladder.l5': 'Выпущено',
  'mk.density': 'Плотность проверки {level}\u00A0из\u00A05',
  'mk.verdict.accepted': 'Принято',
  'mk.verdict.qualified': 'Принято с\u00A0оговоркой',
  'mk.verdict.revised': 'Пересмотрено',
  'mk.verdict.blocked': 'Заблокировано',
  'mk.verdict.rejected': 'Отклонено',
  'mk.verdict.deferred': 'Отложено',

  'mk.claim.c1.title': 'Замена заряда сохраняет связывание с\u00A0лизоцимом',
  'mk.claim.c1.requested': 'Замена безвредна для связывания в\u00A0любой конструкции.',
  'mk.claim.c1.scope': 'Две демонстрационные конструкции, один анализ, один оператор.',
  'mk.claim.c1.uncertainty': 'Двукратный разброс между повторами, всего три измерения.',
  'mk.claim.c1.next': 'Референсный анализ со\u00A0вторым оператором.',
  'mk.claim.c1.needs': 'Контрольная группа и\u00A0один повтор вторым оператором.',
  'mk.claim.c2.title': 'Растворимость растёт на\u00A0полмиллиграмма на\u00A0миллилитр',
  'mk.claim.c2.requested': 'Растворимость растёт для всего семейства вариантов.',
  'mk.claim.c2.scope': 'Одна демонстрационная партия, несовпадающий буфер.',
  'mk.claim.c2.uncertainty': 'Разницу может объяснять один только буфер.',
  'mk.claim.c2.next': 'Повторить в\u00A0совпадающем буфере на\u00A0трёх партиях.',
  'mk.claim.c2.needs': 'Источник для каждого числа в\u00A0записи партии.',
  'mk.claim.c3.title': 'Исходный Fab плавится около 71\u00A0градуса Цельсия',
  'mk.claim.c3.requested': 'Исходный Fab стабилен до\u00A071\u00A0градуса Цельсия.',
  'mk.claim.c3.scope': 'Три демонстрационных запуска, два прибора, одна лаборатория.',
  'mk.claim.c3.uncertainty': 'Полградуса между приборами.',
  'mk.claim.c3.next': 'Работа завершена: утверждение выпущено.',
  'mk.claim.c3.needs': 'Ничего: утверждение на\u00A0верхней ступени.',
  'mk.claim.c4.title': 'Бороздка за\u00A0CDR L1 связывает лиганд',
  'mk.claim.c4.requested': 'Бороздка\u00A0— пригодный аллостерический участок.',
  'mk.claim.c4.scope': 'Одна кристаллическая форма и\u00A0один расчёт стыковки.',
  'mk.claim.c4.uncertainty': 'Артефакт кристалла не\u00A0исключён.',
  'mk.claim.c4.next': 'Вторая кристаллическая форма до\u00A0любого анализа.',
  'mk.claim.c4.needs': 'Воспроизведение в\u00A0независимой кристаллической форме.',

  'mk.evidence.heading': 'Наблюдения',
  'mk.evidence.col.observation': 'Наблюдение',
  'mk.evidence.col.source': 'Источник',
  'mk.evidence.col.recorded': 'Записано',
  'mk.evidence.col.claim': 'Утверждение',
  'mk.evidence.col.density': 'Плотность',
  'mk.evidence.open': 'Выберите строку, чтобы открыть цепочку.',
  'mk.evidence.trace': 'Цепочка от\u00A0утверждения к\u00A0доказательству',
  'mk.evidence.trace.hint': 'Каждый шаг ниже\u00A0— демонстрационные данные прототипа.',
  'mk.evidence.e1.observation': 'Связывание в\u00A0пределах двукратного отклонения от\u00A0исходного для варианта A.',
  'mk.evidence.e1.source': 'Демонстрационный запуск анализа 18.09.2026, планшет 3.',
  'mk.evidence.e1.trace': 'Показание планшета, затем подгонка, затем утверждение.',
  'mk.evidence.e2.observation': 'Связывание в\u00A0пределах двукратного отклонения от\u00A0исходного для варианта B.',
  'mk.evidence.e2.source': 'Демонстрационный запуск анализа 19.09.2026, планшет 1.',
  'mk.evidence.e2.trace': 'Та\u00A0же схема планшета, что и\u00A0у\u00A0варианта A, тот\u00A0же оператор.',
  'mk.evidence.e3.observation': 'Точка плавления 71,2\u00A0градуса Цельсия на\u00A0двух приборах.',
  'mk.evidence.e3.source': 'Демонстрационный термический запуск 21.09.2026.',
  'mk.evidence.e3.trace': 'Две кривые приборов усреднены, исходные кривые сохранены.',
  'mk.evidence.e4.observation': 'Растворимость на\u00A00,5\u00A0миллиграмма на\u00A0миллилитр выше исходной.',
  'mk.evidence.e4.source': 'Демонстрационная запись партии 22.09.2026, буфер не\u00A0совпадает.',
  'mk.evidence.e4.trace': 'Всего одно измерение, и\u00A0буфер не\u00A0был согласован.',
  'mk.evidence.e5.observation': 'Плотность в\u00A0бороздке в\u00A0одной кристаллической форме.',
  'mk.evidence.e5.source': 'Демонстрационная карта 24.09.2026, контур на\u00A0одной сигме.',
  'mk.evidence.e5.trace': 'Карта, затем поза стыковки, затем отложенное утверждение.',

  'mk.activity.heading': 'Ход работы',
  'mk.activity.derived': 'производное',
  'mk.activity.a1': 'Планировщик открыл маршрут замены заряда и\u00A0назвал условие опровержения.',
  'mk.activity.a2': 'Рецензент сузил первое утверждение до\u00A0двух конструкций и\u00A0одного анализа.',
  'mk.activity.a3': 'Плотность проверки первого утверждения выросла до\u00A0трёх из\u00A0пяти.',
  'mk.activity.a4': 'Оппонент запросил вторую кристаллическую форму до\u00A0любого анализа.',
  'mk.activity.a5': 'Релиз остался закрыт: второе утверждение ниже требуемой ступени.',
  'mk.activity.a6': 'Рисунок отправлен в\u00A0очередь согласования и\u00A0ждёт ответа.',

  'mk.approvals.heading': 'По\u00A0одному согласованию за\u00A0раз',
  'mk.approvals.waiting': 'Ещё {count}\u00A0в\u00A0очереди после этого',
  'mk.approval.ap1.title': 'Рисунок контактного участка, раунд 3',
  'mk.approval.ap1.changed': 'Панель контактного участка перекрашена, масштабная линейка сдвинута.',
  'mk.approvals.baseline': 'Исходное изображение',
  'mk.approvals.candidate': 'Новое изображение',
  'mk.approvals.diff': 'Сравнение',
  'mk.approvals.placeholder': 'Место для изображения',
  'mk.approvals.changed': 'Что изменилось',
  'mk.approvals.checks': 'Детерминированные проверки',
  'mk.approvals.blocking': 'Блокирует',
  'mk.approval.check.k1': 'Длина масштабной линейки совпадает с\u00A0заявленным увеличением.',
  'mk.approval.check.k2': 'Подписи остатков совпадают с\u00A0нумерацией в\u00A01DQJ.',
  'mk.approval.check.k3': 'Контраст измерен на\u00A0обеих палитрах.',
  'mk.approvals.vlm': 'Замечание модели зрения (рекомендательное)',
  'mk.approvals.vlm.note': 'Модель зрения считает панель более ясной, но\u00A0сама по\u00A0себе это не\u00A0решение.',
  'mk.approvals.reject_note': 'Причина отклонения',
  'mk.approvals.reject_hint': 'Без причины отклонение не\u00A0записывается.',

  'mk.release.heading': 'Решение о\u00A0релизе',
  'mk.release.col.claim': 'Утверждение',
  'mk.release.col.required': 'Нужная ступень',
  'mk.release.col.reached': 'Достигнутая ступень',
  'mk.release.export': 'Выгрузить релизный комплект',
  'mk.release.blocked': 'Выгрузка закрыта, пока хотя\u00A0бы одно утверждение ниже нужной ступени.',

  'mk.settings.seats': 'Роли',
  'mk.settings.connectors': 'Коннекторы',
  'mk.settings.configure': 'Настроить с\u00A0помощью модели',
  'mk.settings.appearance': 'Оформление',
  'mk.seat.provider': 'Поставщик',
  'mk.seat.model': 'Модель',
  'mk.seat.effort': 'Глубина рассуждения',
  'mk.seat.credential': 'Доступ',
  'mk.seat.credential.ready': 'Доступ сохранён',
  'mk.seat.credential.missing': 'Доступа пока нет',
  'mk.seat.no_secrets': 'Секреты вводятся в\u00A0настольном приложении, а\u00A0не\u00A0на\u00A0этой странице.',
  'mk.seat.edit': 'Изменить роль',
  'mk.effort.low': 'Низкая',
  'mk.effort.medium': 'Средняя',
  'mk.effort.high': 'Высокая',
  'mk.seat.planner.title': 'Планировщик',
  'mk.seat.planner.role': 'Открывает маршруты, называет условия опровержения и\u00A0заказывает проверку.',
  'mk.seat.reviewer.title': 'Рецензент',
  'mk.seat.reviewer.role': 'Сужает каждое утверждение до\u00A0области, которую подтверждают доказательства.',
  'mk.seat.falsifier.title': 'Оппонент',
  'mk.seat.falsifier.role': 'Ищет измерение, которое закрыло\u00A0бы маршрут.',
  'mk.seat.vision.title': 'Визуальный анализ',
  'mk.seat.vision.role': 'Читает рисунки и\u00A0пишет только рекомендательные замечания.',
  'mk.seat.prose.title': 'Текст',
  'mk.seat.prose.role': 'Правит формулировки, не\u00A0трогая утверждения и\u00A0числа.',

  'mk.connector.licence': 'Лицензия',
  'mk.connector.add': 'Добавить любой MCP',
  'mk.connector.add.heading': 'Добавить любой сервер MCP',
  'mk.connector.add.field': 'Команда, URL или server.json',
  'mk.connector.add.hint': 'Вставьте одну команду, один URL или содержимое server.json.',
  'mk.connector.probe': 'Результат проверки',
  'mk.connector.hint': 'Что доступно коннектору',
  'mk.connector.pdb.title': 'RCSB PDB',
  'mk.connector.pdb.note': 'Структуры, лиганды и\u00A0сборки по\u00A0коду доступа.',
  'mk.connector.uniprot.title': 'UniProt',
  'mk.connector.uniprot.note': 'Последовательности, признаки и\u00A0перекрёстные ссылки.',
  'mk.connector.pubmed.title': 'PubMed',
  'mk.connector.pubmed.note': 'Аннотации и\u00A0идентификаторы для литературного следа.',
  'mk.connector.alphafold.title': 'AlphaFold DB',
  'mk.connector.alphafold.note': 'Предсказанные модели с\u00A0уверенностью по\u00A0остаткам.',
  'mk.connector.sabdab.title': 'SAbDab',
  'mk.connector.sabdab.note': 'Структуры антител; по\u00A0лицензии нужно решение.',
  'mk.connector.openmm.title': 'OpenMM',
  'mk.connector.openmm.note': 'Локальный расчёт, направляется в\u00A0WSL (Linux).',
  'mk.connector.probe.p1': 'Сервер ответил на\u00A0рукопожатие.',
  'mk.connector.probe.p2': 'Перечислено одиннадцать инструментов.',
  'mk.connector.probe.p3': 'Ни\u00A0один инструмент ещё не\u00A0вызывался.',

  'mk.configure.reason': 'Причина',
  'mk.configure.risk': 'Риск',
  'mk.configure.apply': 'Применить отмеченное',
  'mk.configure.g1.title': 'Перевести роль визуального анализа на\u00A0меньшую модель',
  'mk.configure.g1.reason': 'Рекомендательным замечаниям не\u00A0нужна самая крупная модель.',
  'mk.configure.g1.risk': 'Замечания к\u00A0рисункам станут короче и\u00A0грубее.',
  'mk.configure.g2.title': 'Поднять глубину рассуждения рецензента до\u00A0высокой',
  'mk.configure.g2.reason': 'Сужение области\u00A0— источник большей части переделок.',
  'mk.configure.g2.risk': 'Каждый круг рецензии станет дольше.',
  'mk.configure.g3.title': 'Отключить коннектор SAbDab',
  'mk.configure.g3.reason': 'Его лицензия для этого проекта не\u00A0согласована.',
  'mk.configure.g3.risk': 'Поиск структур антител уйдёт в\u00A0PDB.',

  'mk.appearance.palette': 'Палитра',
  'mk.appearance.language': 'Язык',
  'mk.appearance.font.installed': 'HSE Sans установлен',
  'mk.appearance.font.missing': 'HSE Sans не\u00A0установлен',
  'mk.appearance.font.link': 'Брендбук НИУ ВШЭ',

  'mk.diag.heading': 'Состояние',
  'mk.diag.source': 'Источник',
  'mk.diag.d1.title': 'Сеанс настольного приложения',
  'mk.diag.d1.source': 'Локальная служба на\u00A0порту приложения.',
  'mk.diag.d2.title': 'Доступы к\u00A0моделям',
  'mk.diag.d2.source': 'Хранилище доступов прочитано при старте сеанса.',
  'mk.diag.d3.title': 'Структурные инструменты',
  'mk.diag.d3.source': 'Запускаются в\u00A0WSL (Linux); в\u00A0этом сеансе ничего не\u00A0запускалось.',
  'mk.diag.d4.title': 'Отрисовка рисунков',
  'mk.diag.d4.source': 'Последняя отрисовка завершилась ошибкой.',
  'mk.diag.d5.title': 'Коннектор SAbDab',
  'mk.diag.d5.source': 'Удерживается до\u00A0решения по\u00A0лицензии.',
  'mk.diag.d6.title': 'Графический процессор',
  'mk.diag.d6.source': 'На\u00A0этой машине не\u00A0проверялся.',

  'mk.latex.files': 'Файлы',
  'mk.latex.editor': 'Редактор',
  'mk.latex.preview': 'Просмотр',
  'mk.latex.layout': 'Вёрстка',
  'mk.latex.page': 'Страница {n}',
  'mk.latex.qa': 'Проверка страницы',
  'mk.latex.qa.note': 'Две переполненные строки на\u00A0первой странице.',
  'mk.latex.tokens': 'Образец подсветки',
  'mk.latex.token.macro': 'макрос',
  'mk.latex.token.math': 'формула',
  'mk.latex.token.comment': 'комментарий',
  'mk.latex.font': 'Гарнитура',
  'mk.latex.size': 'Кегль в\u00A0пунктах',
  'mk.latex.leading': 'Интерлиньяж в\u00A0пунктах',
  'mk.latex.paragraph': 'Отбивка абзаца в\u00A0пунктах',
  'mk.latex.margins': 'Поле в\u00A0миллиметрах',
  'mk.latex.columns': 'Колонки',
  'mk.latex.hyphen.en': 'Английские переносы',
  'mk.latex.hyphen.ru': 'Русские переносы',
  'mk.latex.sample': 'Образец абзаца',
  'mk.latex.sample.text': 'Контактный участок демонстрационного комплекса скрывает широкий гидрофобный участок, поэтому одиночная замена заряда оценивается по\u00A0измеренному интерфейсу, а\u00A0не\u00A0по\u00A0предсказанию.',
  'mk.latex.f1': 'Корень документа',
  'mk.latex.f2': 'Раздел о\u00A0контактном участке',
  'mk.latex.f3': 'Раздел об\u00A0аллостерической бороздке',
  'mk.latex.f4': 'Рисунок лестницы',
  'mk.latex.f5': 'Библиография',

  'mk.logos.heading': 'Варианты логотипа',
  'mk.logos.light': 'Светлый фон',
  'mk.logos.dark': 'Тёмный фон',
  'mk.logos.use': 'Поставить в\u00A0шапку',
  'mk.logos.in_use': 'Используется',
  'mk.logos.sizes': 'Размеры: 256, 64, 32\u00A0и\u00A016\u00A0пикселей.',
  'mk.logos.group.snoggo': 'Snöggo',
  'mk.logos.group.gpt-image': 'GPT-Image',
  'mk.logos.group.biorender': 'BioRender',
  'mk.logos.group.geometric': 'Геометрические',
  'mk.logo.snoggo-tile': 'Плитка Snöggo',
  'mk.logo.snoggo-mark-mono': 'Snöggo, один цвет',
  'mk.logo.arc-a-mark': 'Открытая дуга',
  'mk.logo.arc-a-tile': 'Открытая дуга на\u00A0синем',
  'mk.logo.arc-a-tile-ink': 'Открытая дуга на\u00A0чёрном',
  'mk.logo.arc-b-mark': 'Вложенные дуги',
  'mk.logo.arc-b-tile': 'Вложенные дуги на\u00A0синем',
  'mk.logo.arc-b-tile-ink': 'Вложенные дуги на\u00A0чёрном',
  'mk.logo.arc-c-mark': 'Монограмма-арка',
  'mk.logo.arc-c-tile': 'Монограмма-арка на\u00A0синем',
  'mk.logo.arc-c-tile-ink': 'Монограмма-арка на\u00A0чёрном',
  'mk.logo.gpt-01-tile': 'Вариант GPT-Image 1',
  'mk.logo.gpt-01-mark': 'Вариант GPT-Image 1, знак',
  'mk.logo.gpt-02-tile': 'Вариант GPT-Image 2',
  'mk.logo.gpt-02-mark': 'Вариант GPT-Image 2, знак',
  'mk.logo.gpt-03-tile': 'Вариант GPT-Image 3',
  'mk.logo.gpt-03-mark': 'Вариант GPT-Image 3, знак',
  'mk.logo.gpt-04-tile': 'Вариант GPT-Image 4',
  'mk.logo.gpt-04-mark': 'Вариант GPT-Image 4, знак',
  'mk.logo.gpt-05-tile': 'Вариант GPT-Image 5',
  'mk.logo.gpt-05-mark': 'Вариант GPT-Image 5, знак',
  'mk.logo.gpt-06-tile': 'Вариант GPT-Image 6',
  'mk.logo.gpt-06-mark': 'Вариант GPT-Image 6, знак',
  'mk.logo.gpt-07-tile': 'Вариант GPT-Image 7',
  'mk.logo.gpt-07-mark': 'Вариант GPT-Image 7, знак',
  'mk.logo.gpt-08-tile': 'Вариант GPT-Image 8',
  'mk.logo.gpt-08-mark': 'Вариант GPT-Image 8, знак',
  'mk.logo.biorender-arch-tile': 'Арка BioRender',
  'mk.logo.biorender-arch-mark': 'Арка BioRender, знак',
  'mk.logo.biorender-pocket-tile': 'Дуга кармана BioRender',
  'mk.logo.biorender-pocket-mark': 'Дуга кармана BioRender, знак',
};
