// Prototype vocabulary. Sentence case; helper lines stay under 90 characters.
export default {
  'mk.app.title': 'Arc Science prototype',
  'mk.screen.label': 'Screen',
  'mk.screen.research': 'Research cockpit',
  'mk.screen.settings': 'Settings',
  'mk.screen.diagnostics': 'Diagnostics',
  'mk.screen.latex': 'LaTeX studio',
  'mk.screen.logos': 'Logo candidates',
  'mk.screen.placeholder': 'This workspace is outside the S0 prototype.',

  'mk.search.open': 'Search or run',
  'mk.search.heading': 'Search or run',
  'mk.search.field': 'Workspaces, missions and actions',
  'mk.search.hint': 'Type a mission name or an action.',
  'mk.search.group.workspaces': 'Workspaces',
  'mk.search.group.missions': 'Missions',
  'mk.search.group.actions': 'Actions',
  'mk.search.action.new_route': 'Open a new route',
  'mk.search.action.approvals': 'Go to the approval queue',
  'mk.search.action.export': 'Export the release bundle',
  'mk.logo.slot': 'Header logo',

  'mk.missions.heading': 'Missions',
  'mk.mission.question': 'Question',
  'mk.mission.round': 'Round {current} of {total}',
  'mk.mission.state.active': 'Waiting for approval',
  'mk.mission.state.paused': 'Paused',
  'mk.mission.state.done': 'Closed',
  'mk.mission.state.running': 'Running',

  'mk.m1.title': 'Charge swap at the HyHEL-63 contact site',
  'mk.m1.question': 'Does a charge swap at the 1DQJ contact site keep lysozyme binding while raising solubility?',
  'mk.m2.title': 'Allosteric groove on the light chain',
  'mk.m2.question': 'Is the groove behind CDR L1 a real allosteric site or a crystal artefact?',
  'mk.m3.title': 'Thermal stability of the parent Fab',
  'mk.m3.question': 'How far can the parent Fab be heated before the contact site loses its shape?',

  'mk.tab.overview': 'Overview',
  'mk.tab.routes': 'Routes',
  'mk.tab.claims': 'Claims',
  'mk.tab.evidence': 'Evidence',
  'mk.tab.activity': 'Activity',
  'mk.tab.approvals': 'Approvals',
  'mk.tab.release': 'Release',

  'mk.overview.believe': 'What we believe',
  'mk.overview.believe.1': 'The contact site tolerates one charge swap without losing lysozyme binding.',
  'mk.overview.believe.2': 'Solubility rises with the swap, measured on three example batches.',
  'mk.overview.believe.3': 'The allosteric groove stays unexplained and is held apart from the main claim.',
  'mk.overview.change': 'What would change it',
  'mk.overview.change.1': 'A binding drop beyond tenfold in the reference assay.',
  'mk.overview.change.2': 'Any solubility gain that disappears once the buffer is matched.',
  'mk.overview.change.3': 'A second crystal form without the groove.',
  'mk.overview.next': 'Next',
  'mk.overview.next.1': 'Run the reference binding assay on the two surviving variants.',
  'mk.overview.next.2': 'Repeat the solubility reading in matched buffer.',
  'mk.overview.next.3': 'Ask for a second crystal form before the groove is claimed.',

  'mk.lane.focused': 'Focused',
  'mk.lane.warm': 'Warm',
  'mk.lane.parked': 'Parked',
  'mk.route.hypothesis': 'Hypothesis',
  'mk.route.falsifier': 'Falsifier',
  'mk.route.observation': 'Last observation',
  'mk.route.next': 'Next test',
  'mk.route.basis': 'Basis',

  'mk.route.r1.title': 'Charge swap at the contact site',
  'mk.route.r1.hypothesis': 'Swapping one buried charge raises solubility and leaves binding intact.',
  'mk.route.r1.falsifier': 'Binding falls more than tenfold in the reference assay.',
  'mk.route.r1.observation': 'Two of three example variants kept binding within twofold.',
  'mk.route.r1.next': 'Reference binding assay on both surviving variants.',
  'mk.route.r1.basis': 'Interface area from 1DQJ plus two published swaps.',
  'mk.route.r2.title': 'Matched buffer solubility',
  'mk.route.r2.hypothesis': 'The solubility gain survives once the buffer is matched.',
  'mk.route.r2.falsifier': 'The gain disappears at matched ionic strength.',
  'mk.route.r2.observation': 'Only one batch has been read in matched buffer so far.',
  'mk.route.r2.next': 'Read the two remaining batches in matched buffer.',
  'mk.route.r2.basis': 'Example batch records from the prototype dataset.',
  'mk.route.r3.title': 'Allosteric groove behind CDR L1',
  'mk.route.r3.hypothesis': 'The groove binds a small ligand and shifts the contact site.',
  'mk.route.r3.falsifier': 'No density in the groove in a second crystal form.',
  'mk.route.r3.observation': 'The groove appears in one crystal form only.',
  'mk.route.r3.next': 'Ask for a second crystal form before spending assay time.',
  'mk.route.r3.basis': 'One example map and a docking run.',
  'mk.route.r4.title': 'Framework back mutation',
  'mk.route.r4.hypothesis': 'A framework back mutation recovers the lost half kilocalorie.',
  'mk.route.r4.falsifier': 'Stability stays flat across the back mutation panel.',
  'mk.route.r4.observation': 'No observation yet; the panel has not been ordered.',
  'mk.route.r4.next': 'Order the four-variant panel once the assay slot is free.',
  'mk.route.r4.basis': 'Prediction only, with no measurement behind it.',
  'mk.route.r5.title': 'Glycan shielding of the contact site',
  'mk.route.r5.hypothesis': 'An added glycan shields the contact site and cuts aggregation.',
  'mk.route.r5.falsifier': 'Aggregation is unchanged with the glycan in place.',
  'mk.route.r5.observation': 'Parked after the first pass found no free sequon.',
  'mk.route.r5.next': 'Revisit only if the charge swap route stalls.',
  'mk.route.r5.basis': 'Sequence scan of the example construct.',

  'mk.claim.requested': 'Requested',
  'mk.claim.scope': 'Supported scope',
  'mk.claim.uncertainty': 'Uncertainty',
  'mk.claim.next': 'Next experiment',
  'mk.ladder': 'Validation ladder',
  'mk.ladder.reached': 'Reached {rung}',
  'mk.ladder.needs': 'Next rung needs',
  'mk.ladder.l0': 'Stated',
  'mk.ladder.l1': 'Sourced',
  'mk.ladder.l2': 'Reproduced',
  'mk.ladder.l3': 'Controlled',
  'mk.ladder.l4': 'Independent',
  'mk.ladder.l5': 'Released',
  'mk.density': 'Verification density {level} of 5',
  'mk.verdict.accepted': 'Accepted',
  'mk.verdict.qualified': 'Qualified',
  'mk.verdict.revised': 'Revised',
  'mk.verdict.blocked': 'Blocked',
  'mk.verdict.rejected': 'Rejected',
  'mk.verdict.deferred': 'Deferred',

  'mk.claim.c1.title': 'The charge swap keeps lysozyme binding',
  'mk.claim.c1.requested': 'The swap is harmless to binding in every construct.',
  'mk.claim.c1.scope': 'Two example constructs, one assay, one operator.',
  'mk.claim.c1.uncertainty': 'Twofold spread between replicates, three readings in total.',
  'mk.claim.c1.next': 'Reference assay with a second operator.',
  'mk.claim.c1.needs': 'A control arm and one repeat by a second operator.',
  'mk.claim.c2.title': 'Solubility rises by half a milligram per millilitre',
  'mk.claim.c2.requested': 'Solubility rises for the whole variant family.',
  'mk.claim.c2.scope': 'One example batch, unmatched buffer.',
  'mk.claim.c2.uncertainty': 'Buffer differences alone could explain the reading.',
  'mk.claim.c2.next': 'Repeat in matched buffer on three batches.',
  'mk.claim.c2.needs': 'A source for every number in the batch record.',
  'mk.claim.c3.title': 'The parent Fab melts near 71 degrees Celsius',
  'mk.claim.c3.requested': 'The parent Fab is stable to 71 degrees Celsius.',
  'mk.claim.c3.scope': 'Three example runs, two instruments, one laboratory.',
  'mk.claim.c3.uncertainty': 'Half a degree between instruments.',
  'mk.claim.c3.next': 'No further work; the claim is released.',
  'mk.claim.c3.needs': 'Nothing; this claim sits on the top rung.',
  'mk.claim.c4.title': 'The groove behind CDR L1 binds a ligand',
  'mk.claim.c4.requested': 'The groove is a usable allosteric site.',
  'mk.claim.c4.scope': 'One crystal form and one docking run.',
  'mk.claim.c4.uncertainty': 'A crystal artefact has not been ruled out.',
  'mk.claim.c4.next': 'Second crystal form before any assay time.',
  'mk.claim.c4.needs': 'A reproduction in an independent crystal form.',

  'mk.evidence.heading': 'Observations',
  'mk.evidence.col.observation': 'Observation',
  'mk.evidence.col.source': 'Source',
  'mk.evidence.col.recorded': 'Recorded',
  'mk.evidence.col.claim': 'Claim',
  'mk.evidence.col.density': 'Density',
  'mk.evidence.open': 'Select a row to open its trace.',
  'mk.evidence.trace': 'Claim to evidence trace',
  'mk.evidence.trace.hint': 'Every step below is example data held in the prototype.',
  'mk.evidence.e1.observation': 'Binding within twofold of the parent for variant A.',
  'mk.evidence.e1.source': 'Example assay run 2026-09-18, plate 3.',
  'mk.evidence.e1.trace': 'Plate reading, then the fit, then the claim it supports.',
  'mk.evidence.e2.observation': 'Binding within twofold of the parent for variant B.',
  'mk.evidence.e2.source': 'Example assay run 2026-09-19, plate 1.',
  'mk.evidence.e2.trace': 'Same plate layout as variant A, read by the same operator.',
  'mk.evidence.e3.observation': 'Melting point 71.2 degrees Celsius on two instruments.',
  'mk.evidence.e3.source': 'Example thermal run 2026-09-21.',
  'mk.evidence.e3.trace': 'Two instrument traces averaged, with the raw curves kept.',
  'mk.evidence.e4.observation': 'Solubility 0.5 milligrams per millilitre above the parent.',
  'mk.evidence.e4.source': 'Example batch record 2026-09-22, unmatched buffer.',
  'mk.evidence.e4.trace': 'One reading only, and the buffer was not matched.',
  'mk.evidence.e5.observation': 'Density in the groove in one crystal form.',
  'mk.evidence.e5.source': 'Example map 2026-09-24, contour at one sigma.',
  'mk.evidence.e5.trace': 'Map, then docking pose, then the deferred claim.',

  'mk.activity.heading': 'Activity',
  'mk.activity.derived': 'derived',
  'mk.activity.a1': 'The planner opened the charge swap route and named its falsifier.',
  'mk.activity.a2': 'The reviewer narrowed claim one to two constructs and one assay.',
  'mk.activity.a3': 'Verification density for claim one rose to three of five.',
  'mk.activity.a4': 'The falsifier asked for a second crystal form before any assay time.',
  'mk.activity.a5': 'The release gate stayed shut because claim two sits below its required rung.',
  'mk.activity.a6': 'A figure was sent to the approval queue and is waiting for a decision.',

  'mk.approvals.heading': 'One decision at a time',
  'mk.approvals.waiting': '{count} more waiting after this one',
  'mk.approval.ap1.title': 'Contact site figure, round 3',
  'mk.approval.ap1.changed': 'The contact site panel was recoloured and the scale bar moved.',
  'mk.approvals.baseline': 'Baseline image',
  'mk.approvals.candidate': 'Candidate image',
  'mk.approvals.diff': 'Difference view',
  'mk.approvals.placeholder': 'Image placeholder',
  'mk.approvals.changed': 'What changed',
  'mk.approvals.checks': 'Deterministic checks',
  'mk.approvals.blocking': 'Blocking',
  'mk.approval.check.k1': 'Scale bar length matches the stated magnification.',
  'mk.approval.check.k2': 'Residue labels match the numbering in 1DQJ.',
  'mk.approval.check.k3': 'Colour contrast measured on both palettes.',
  'mk.approvals.vlm': 'Vision note, advisory only',
  'mk.approvals.vlm.note': 'The vision seat reads the panel as clearer, which decides nothing on its own.',
  'mk.approvals.reject_note': 'Reason for rejection',
  'mk.approvals.reject_hint': 'A reason is required before a rejection is recorded.',

  'mk.release.heading': 'Release decision',
  'mk.release.col.claim': 'Claim',
  'mk.release.col.required': 'Required rung',
  'mk.release.col.reached': 'Reached rung',
  'mk.release.export': 'Export release bundle',
  'mk.release.blocked': 'Export stays off while any claim sits below its required rung.',

  'mk.settings.seats': 'Seats',
  'mk.settings.connectors': 'Connectors',
  'mk.settings.configure': 'Configure with a model',
  'mk.settings.appearance': 'Appearance',
  'mk.seat.provider': 'Provider',
  'mk.seat.model': 'Model',
  'mk.seat.effort': 'Reasoning effort',
  'mk.seat.credential': 'Credential',
  'mk.seat.credential.ready': 'Credential on file',
  'mk.seat.credential.missing': 'No credential yet',
  'mk.seat.no_secrets': 'Secrets are entered in the desktop app, never on this page.',
  'mk.seat.edit': 'Edit seat',
  'mk.effort.low': 'Low',
  'mk.effort.medium': 'Medium',
  'mk.effort.high': 'High',
  'mk.seat.planner.title': 'Planner',
  'mk.seat.planner.role': 'Opens routes, names falsifiers and orders the next test.',
  'mk.seat.reviewer.title': 'Reviewer',
  'mk.seat.reviewer.role': 'Narrows every claim to the scope its evidence carries.',
  'mk.seat.falsifier.title': 'Falsifier',
  'mk.seat.falsifier.role': 'Looks for the reading that would end the route.',
  'mk.seat.vision.title': 'Vision',
  'mk.seat.vision.role': 'Reads figures and writes advisory notes only.',
  'mk.seat.prose.title': 'Prose',
  'mk.seat.prose.role': 'Edits wording without touching claims or numbers.',

  'mk.connector.licence': 'Licence',
  'mk.connector.add': 'Add any MCP',
  'mk.connector.add.heading': 'Add any MCP server',
  'mk.connector.add.field': 'Command, URL or server.json',
  'mk.connector.add.hint': 'Paste one command, one URL or the contents of server.json.',
  'mk.connector.probe': 'Probe result',
  'mk.connector.hint': 'What this connector reaches',
  'mk.connector.pdb.title': 'RCSB PDB',
  'mk.connector.pdb.note': 'Structures, ligands and assemblies by accession.',
  'mk.connector.uniprot.title': 'UniProt',
  'mk.connector.uniprot.note': 'Sequences, features and cross references.',
  'mk.connector.pubmed.title': 'PubMed',
  'mk.connector.pubmed.note': 'Abstracts and identifiers for the literature trail.',
  'mk.connector.alphafold.title': 'AlphaFold DB',
  'mk.connector.alphafold.note': 'Predicted models with per residue confidence.',
  'mk.connector.sabdab.title': 'SAbDab',
  'mk.connector.sabdab.note': 'Antibody structures; the licence needs a decision.',
  'mk.connector.openmm.title': 'OpenMM',
  'mk.connector.openmm.note': 'Local simulation, routed to the Linux side.',
  'mk.connector.probe.p1': 'The server answered the handshake.',
  'mk.connector.probe.p2': 'Eleven tools were listed and named.',
  'mk.connector.probe.p3': 'No tool has been called yet.',

  'mk.configure.reason': 'Reason',
  'mk.configure.risk': 'Risk',
  'mk.configure.apply': 'Apply ticked changes',
  'mk.configure.g1.title': 'Move the vision seat to a smaller model',
  'mk.configure.g1.reason': 'Advisory notes do not need the largest model.',
  'mk.configure.g1.risk': 'Figure notes become shorter and blunter.',
  'mk.configure.g2.title': 'Raise reviewer effort to high',
  'mk.configure.g2.reason': 'Scope narrowing is where most rework starts.',
  'mk.configure.g2.risk': 'Each review round takes longer.',
  'mk.configure.g3.title': 'Turn off the SAbDab connector',
  'mk.configure.g3.reason': 'Its licence has not been cleared for this project.',
  'mk.configure.g3.risk': 'Antibody structure lookups fall back to the PDB.',

  'mk.appearance.palette': 'Palette',
  'mk.appearance.language': 'Language',
  'mk.appearance.font.installed': 'HSE Sans installed',
  'mk.appearance.font.missing': 'HSE Sans not installed',
  'mk.appearance.font.link': 'HSE brandbook',

  'mk.diag.heading': 'Status',
  'mk.diag.source': 'Source',
  'mk.diag.d1.title': 'Desktop session',
  'mk.diag.d1.source': 'Local service on the desktop port.',
  'mk.diag.d2.title': 'Model credentials',
  'mk.diag.d2.source': 'Credential store read at session start.',
  'mk.diag.d3.title': 'Structure tools',
  'mk.diag.d3.source': 'Linux side; nothing has been run this session.',
  'mk.diag.d4.title': 'Figure renderer',
  'mk.diag.d4.source': 'Last render exited with an error.',
  'mk.diag.d5.title': 'SAbDab connector',
  'mk.diag.d5.source': 'Held until the licence question is settled.',
  'mk.diag.d6.title': 'GPU',
  'mk.diag.d6.source': 'Not probed on this machine.',

  'mk.latex.files': 'Files',
  'mk.latex.editor': 'Editor',
  'mk.latex.preview': 'Preview',
  'mk.latex.layout': 'Layout',
  'mk.latex.page': 'Page {n}',
  'mk.latex.qa': 'Page QA',
  'mk.latex.qa.note': 'Two overfull lines on page one.',
  'mk.latex.tokens': 'Highlighting sample',
  'mk.latex.token.macro': 'macro',
  'mk.latex.token.math': 'maths',
  'mk.latex.token.comment': 'comment',
  'mk.latex.font': 'Font family',
  'mk.latex.size': 'Size in points',
  'mk.latex.leading': 'Leading in points',
  'mk.latex.paragraph': 'Paragraph spacing in points',
  'mk.latex.margins': 'Margin in millimetres',
  'mk.latex.columns': 'Columns',
  'mk.latex.hyphen.en': 'English hyphenation',
  'mk.latex.hyphen.ru': 'Russian hyphenation',
  'mk.latex.sample': 'Preview paragraph',
  'mk.latex.sample.text': 'The contact site of the example complex buries a wide hydrophobic patch, so a single charge swap is judged against the measured interface rather than against a prediction.',
  'mk.latex.f1': 'Document root',
  'mk.latex.f2': 'Contact site section',
  'mk.latex.f3': 'Allosteric groove section',
  'mk.latex.f4': 'Ladder figure',
  'mk.latex.f5': 'Bibliography',

  'mk.logos.heading': 'Logo candidates',
  'mk.logos.light': 'Light background',
  'mk.logos.dark': 'Dark background',
  'mk.logos.use': 'Use as header logo',
  'mk.logos.in_use': 'In use',
  'mk.logos.sizes': 'Sizes: 256, 64, 32 and 16 pixels.',
  'mk.logos.group.snoggo': 'Snöggo',
  'mk.logos.group.gpt-image': 'GPT-Image',
  'mk.logos.group.biorender': 'BioRender',
  'mk.logos.group.geometric': 'Geometric',
  'mk.logo.snoggo-tile': 'Snöggo tile',
  'mk.logo.snoggo-mark-mono': 'Snöggo, one colour',
  'mk.logo.arc-a-mark': 'Open arc mark',
  'mk.logo.arc-a-tile': 'Open arc on blue',
  'mk.logo.arc-a-tile-ink': 'Open arc on ink',
  'mk.logo.arc-b-mark': 'Nested arcs mark',
  'mk.logo.arc-b-tile': 'Nested arcs on blue',
  'mk.logo.arc-b-tile-ink': 'Nested arcs on ink',
  'mk.logo.arc-c-mark': 'Arch monogram mark',
  'mk.logo.arc-c-tile': 'Arch monogram on blue',
  'mk.logo.arc-c-tile-ink': 'Arch monogram on ink',
  'mk.logo.gpt-01-tile': 'GPT-Image variant 1',
  'mk.logo.gpt-01-mark': 'GPT-Image variant 1 mark',
  'mk.logo.gpt-02-tile': 'GPT-Image variant 2',
  'mk.logo.gpt-02-mark': 'GPT-Image variant 2 mark',
  'mk.logo.gpt-03-tile': 'GPT-Image variant 3',
  'mk.logo.gpt-03-mark': 'GPT-Image variant 3 mark',
  'mk.logo.gpt-04-tile': 'GPT-Image variant 4',
  'mk.logo.gpt-04-mark': 'GPT-Image variant 4 mark',
  'mk.logo.gpt-05-tile': 'GPT-Image variant 5',
  'mk.logo.gpt-05-mark': 'GPT-Image variant 5 mark',
  'mk.logo.gpt-06-tile': 'GPT-Image variant 6',
  'mk.logo.gpt-06-mark': 'GPT-Image variant 6 mark',
  'mk.logo.gpt-07-tile': 'GPT-Image variant 7',
  'mk.logo.gpt-07-mark': 'GPT-Image variant 7 mark',
  'mk.logo.gpt-08-tile': 'GPT-Image variant 8',
  'mk.logo.gpt-08-mark': 'GPT-Image variant 8 mark',
  'mk.logo.biorender-arch-tile': 'BioRender arch',
  'mk.logo.biorender-arch-mark': 'BioRender arch mark',
  'mk.logo.biorender-pocket-tile': 'BioRender pocket arc',
  'mk.logo.biorender-pocket-mark': 'BioRender pocket arc mark',
};
